### ISSUE TITLE
predatoR error message

### ISSUE THREAD

**Issue by playerpool** [berkgurdamar/predatoR#1]
Hello,

I just downloaded your predatoR package and ran a quick test. I got the following error. Any ideas?

> df <- data.frame(PDB_ID, Chain, Position, Orig_AA, Mut_AA)
> predatoR::predatoR(df, PDB_path = NULL, n_threads = 10, gene_name_info = FALSE, distance_cutoff = 7, network_approach = "all")
trying URL 'https://files.rcsb.org/download/5I4Z.pdb'
downloaded 370 KB

   PDB has ALT records, taking A only, rm.alt=TRUE
STEP:
Reading PDB:			DONE
PDB ID:				5I4Z
Position(s):			19, 20
Edge List:			DONE
Degree Score:			DONE
Eigen Centrality Score:		DONE
Shortest Path Score:		DONE
Betweenness Score:		DONE
Clique Score:			DONE
PageRank Score:			DONE
GNOMAD Scores:			DONE
BLOSUM62 Score:			DONE
KEGG Pathway Number:		DONE
Genic Intolerance Score:	DONE
GO Term Number:			DONE
DisGeNET Disease Number:	DONE
Gene Essentiality Score:	DONE
GTEx Score:			DONE
Amino Acid Features:		DONE
Error in caret::predict.train(caret_adaboost_all, final_df, type = "prob") : 
  object 'caret_adaboost_all' not found

**Comment by berkgurdamar** [comment]
Hello,

Can you try with importing library first with `library(predatoR)`?

**Comment by playerpool** [comment]
That fixed it, thank you.

**Comment by playerpool** [comment]
I'm having another issue, see below. I've tried altering the PDB id to include an '_1' to direct to a specific chain but it gave the same errors. Any idea? Maybe it ignored the chain I told it to use?

> predatoR::predatoR(df, PDB_path = NULL, n_threads = 10, gene_name_info = FALSE, distance_cutoff = 7, network_approach = "all")
trying URL 'https://files.rcsb.org/download/8EFQ.pdb'
downloaded 612 KB

STEP:
Reading PDB:			DONE
PDB ID:				8EFQ
Position(s):			180, 254, 103, 73, 146, 151, 154, 189, 204, 191, 259
There are multiple amino acids for residue 180 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 254 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 103 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 73 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 146 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 151 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 154 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 189 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 204 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 191 in the PDB file, it will be removed from the query
There are multiple amino acids for residue 259 in the PDB file, it will be removed from the query
Error in predatoR::predatoR(df, PDB_path = NULL, n_threads = 10, gene_name_info = FALSE,  : 
  There is no input for prediction

**Comment by berkgurdamar** [comment]
can you send the input data frame `df`?

**Comment by playerpool** [comment]
[df.csv](https://github.com/berkgurdamar/predatoR/files/10169181/df.csv)

"","PDB_ID","Chain","Position","Orig_AA","Mut_AA"
"1","8EFQ","E",180,"ARG","CYS"
"2","8EFQ","E",254,"GLY","GLU"
"3","8EFQ","E",103,"ALA","ASP"
"4","8EFQ","E",73,"MET","THR"
"5","8EFQ","E",146,"SER","CYS"
"6","8EFQ","E",151,"ASN","ASP"
"7","8EFQ","E",154,"THR","ILE"
"8","8EFQ","E",189,"ASN","LYS"
"9","8EFQ","E",204,"MET","THR"
"10","8EFQ","E",191,"CYS","PHE"
"11","8EFQ","E",259,"ARG","CYS"

**Comment by berkgurdamar** [comment]
PDB 8EFQ does not contain chain "E". You can see the chains with this code
```
pdb <- predatoR::read_PDB("8EFQ")
unique(pdb$chain)
[1] "A" "B" "G" "P" "R"
```
 if you change it to correct chain I think everything will work fine.
